export const inputPlaceholders = {
  name: 'Name',
  lastName: 'Last name',
  division: 'Division',
  jobPosition: 'Job title',
  rate1: 'Rate #1',
  comission1: 'Commision %1',
  rate2: 'Rate #2',
  comission2: 'Comission %2',
  salary: 'Salary',
  positions: 'Positions',
  monthlyHours: 'Monthly hours',
  exchangeRate: 'Exchange rate',
  employerTaxes: 'Employer taxes',
};
